"""empty message

Revision ID: 3d6c84555639
Revises: aa21f19b65c7
Create Date: 2024-11-02 19:36:30.518423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d6c84555639'
down_revision = 'aa21f19b65c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.alter_column('compliance_entries', 'user',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=80),
               nullable=True)
    op.drop_column('compliance_entries', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_entries', sa.Column('message', mysql.VARCHAR(length=255), nullable=False))
    op.alter_column('compliance_entries', 'user',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_table('notification',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
