"""empty message

Revision ID: aa21f19b65c7
Revises: 14feff11ec95
Create Date: 2024-11-02 17:50:33.966514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa21f19b65c7'
down_revision = '14feff11ec95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('compliance_entries', sa.Column('message', sa.String(length=255), nullable=False))
    op.alter_column('compliance_entries', 'user',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compliance_entries', 'user',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=80),
               nullable=True)
    op.drop_column('compliance_entries', 'message')
    op.drop_table('notification')
    # ### end Alembic commands ###
