env:
  CI: false
name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH and Clone Repo
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $EC2_USER@$EC2_HOST "
            cd /home/ubuntu/Compilance-Management || git clone https://github.com/username/Compilance-Management.git /home/ubuntu/Compilance-Management
            cd /home/ubuntu/Compilance-Management
            git pull origin master
          "

      - name: Start Server
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/Compilance-Management
            npm install
            nohup npm start > app.log 2>&1 &
          EOF
