name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH Key for EC2 Access
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | awk '{gsub(/\\n/,"\n")}1' > private_key
          chmod 600 private_key

      - name: Debug: Verify SSH Connection to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key $EC2_USER@$EC2_HOST "echo 'SSH connection successful.'"

      - name: Clone Repository Directly on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          GITHUB_REPO: "https://github.com/Ramgopalhyndavbollepalli/Compilance-Management.git"
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu
            # Remove any existing directory if it exists
            rm -rf Compilance-Management
            # Clone the repository
            git clone $GITHUB_REPO
            cd Compilance-Management
            npm install
          EOF

      - name: Start Application on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/Compilance-Management
            npm start &
          EOF

      - name: Final Debug: Check Running Processes on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key $EC2_USER@$EC2_HOST "ps aux | grep 'node'"
