name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and Deploy
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: "ubuntu"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REPO_URL: "https://github.com/Ramgopalhyndavbollepalli/Compilance-Management.git"
          EC2_APP_DIR: "/home/ubuntu/Compilance-Management"
        run: |
          # Create the SSH private key file with newlines interpreted correctly
          echo -e "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          # SSH into EC2 and pull the latest code, then start the app
          ssh -o StrictHostKeyChecking=no -i private_key $EC2_USER@$EC2_HOST << 'EOF'
            # Clone the repository if it doesn't exist; otherwise, pull the latest changes
            if [ ! -d "$EC2_APP_DIR" ]; then
              git clone $REPO_URL $EC2_APP_DIR
            else
              cd $EC2_APP_DIR
              git pull origin master
            fi

            # Install dependencies and start the application
            cd $EC2_APP_DIR
            npm install
            npm start
          EOF
