name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build React app
        env:
          CI: false  # Ignore warnings as errors during build
        run: |
          npm install
          npm run build

      - name: Upload build to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_APP_DIR: "/home/ubuntu/Compilance-Management"
        run: |
          # Save the SSH private key, ensuring it’s correctly formatted
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > private_key
          chmod 600 private_key

          # Use scp with verbose output for debugging
          scp -v -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i private_key -r ./build/* $EC2_USER@$EC2_HOST:$EC2_APP_DIR

      - name: Start Server with npm
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_APP_DIR: "/home/ubuntu/Compilance-Management"
        run: |
          # SSH into the EC2 instance and start the server
          ssh -v -o StrictHostKeyChecking=no -i private_key $EC2_USER@$EC2_HOST << EOF
            cd $EC2_APP_DIR
            npm start
          EOF
